sudo: required
services:
- docker
install:
  - docker build --pull --no-cache --tag spike:${TRAVIS_BRANCH}_${TRAVIS_PULL_REQUEST} .
script:
  - docker-compose -f docker-compose.ci.yml pull chrome hub && docker-compose -f docker-compose.ci.yml up -d
  - docker-compose -f docker-compose.ci.yml run --rm -w"/home/spike/generator" spike npm run test:integration
after_script:
  - docker-compose -f docker-compose.ci.yml down && docker rmi spike:${TRAVIS_BRANCH}_${TRAVIS_PULL_REQUEST}
